using System;

namespace Iana.MediaTypes
{
    public class Text
    {
        public readonly  string Oned_interleaved_parityfec = "text/1d-interleaved-parityfec"; // [RFC6015]
        public readonly  string cache_manifest = "text/cache-manifest"; //[W3C][Robin_Berjon]
        public readonly  string calendar = "text/calendar"; //[RFC5545]
        public readonly  string css = "text/css"; //[RFC2318]
        public readonly  string csv = "text/csv"; //[RFC4180][RFC7111]
        public readonly  string csv_schema = "text/csv-schema"; //[National_Archives_UK][David_Underdown]
        public readonly  string dns = "text/dns"; //[RFC4027]
        public readonly  string encaprtp = "text/encaprtp"; //[RFC6849]
        public readonly  string example = "text/example"; //[RFC4735]
        public readonly  string fwdred = "text/fwdred"; //[RFC6354]
        public readonly  string grammar_ref_list = "text/grammar-ref-list" ; //[RFC6787]
        public readonly  string html = "text/html"; //[W3C][Robin_Berjon]
        public readonly  string jcr_cnd = "text/jcr-cnd" ; //[Peeter_Piegaze]
        public readonly  string markdown = "text/markdown"; //[RFC7763]
        public readonly  string mizar = "text/mizar"; //[Jesse_Alama]
        public readonly  string n3 = "text/n3"; //[W3C][Eric_Prudhommeaux]
        public readonly  string parameters = "text/parameters"; //[RFC7826]
        public readonly  string provenance_notation = "text/provenance-notation" ; //[W3C][Ivan_Herman]
        public readonly  string prs_fallenstein_rst = "text/prs.fallenstein.rst" ; //[Benja_Fallenstein]
        public readonly  string prs_lines_tag = "text/prs.lines.tag" ; //[John_Lines]
        public readonly  string prs_prop_logic = "text/prs.prop.logic" ; //[Hans-Dieter_A._Hiep]
        public readonly  string raptorfec = "text/raptorfec"; //[RFC6682]
        public readonly  string RED = "text/RED"; //[RFC4102]
        public readonly  string rfc822_headers = "text/rfc822-headers" ; //[RFC6522]
        public readonly  string rtf = "text/rtf"; //[Paul_Lindner]
        public readonly  string rtp_enc_aescm128 = "text/rtp-enc-aescm128" ; //[_3GPP]
        public readonly  string rtploopback = "text/rtploopback"; //[RFC6849]
        public readonly  string rtx = "text/rtx"; //[RFC4588]
        public readonly  string sgml = "text/SGML"; //[RFC1874]
        public readonly  string strings = "text/strings"; //[IEEE-ISTO-PWG-PPP]
        public readonly  string t140 = "text/t140"; //[RFC4103]
        public readonly  string tab_separated_values = "text/tab-separated-values" ; //[Paul_Lindner]
        public readonly  string troff = "text/troff"; //[RFC4263]
        public readonly  string turtle = "text/turtle"; //[W3C][Eric_Prudhommeaux]
        public readonly  string ulpfec = "text/ulpfec"; //[RFC5109]
        public readonly  string uri_list = "text/uri-list" ; //[RFC2483]
        public readonly  string vcard = "text/vcard"; //[RFC6350]
        public readonly  string vnd_a = "text/vnd-a" ; //[Regis_Dehoux]
        public readonly  string vnd_abc = "text/vnd.abc" ; //[Steve_Allen]
        public readonly  string vnd_ascii_art = "text/vnd.ascii-art" ; //[Kim_Scarborough]
        public readonly  string vnd_curl = "text/vnd-curl" ; //[Robert_Byrnes]
        public readonly  string vnd_debian_copyright = "text/vnd.debian.copyright" ; //[Charles_Plessy]
        public readonly  string vnd_DMClientScript = "text/vnd.DMClientScript" ; //[Dan_Bradley]
        public readonly  string vnd_dvb_subtitle = "text/vnd.dvb.subtitle" ; //[Peter_Siebert][Michael_Lagally]
        public readonly  string vnd_esmertec_theme_descriptor = "text/vnd.esmertec.theme-descriptor" ; //[Stefan_Eilemann]
        public readonly  string vnd_fly = "text/vnd.fly" ; //[John-Mark_Gurney]
        public readonly  string vnd_fmi_flexstor = "text/vnd.fmi.flexstor" ; //[Kari_E._Hurtta]
        public readonly  string vnd_graphviz = "text/vnd.graphviz" ; //[John_Ellson]
        public readonly  string vnd_in3d_3dml = "text/vnd.in3d.3dml" ; //[Michael_Powers]
        public readonly  string vnd_in3d_spot = "text/vnd.in3d.spot" ; //[Michael_Powers]
        public readonly  string vnd_IPTC_NewsML = "text/vnd.IPTC.NewsML" ; //[IPTC]
        public readonly  string vnd_IPTC_NITF = "text/vnd.IPTC.NITF" ; //[IPTC]
        public readonly  string vnd_latex_z = "text/vnd.latex-z" ; //[Mikusiak_Lubos]
        public readonly  string vnd_motorola_reflex = "text/vnd.motorola.reflex" ; //[Mark_Patton]
        public readonly  string vnd_ms_mediapackage = "text/vnd.ms-mediapackage" ; //[Jan_Nelson]
        public readonly  string vnd_net2phone_commcenter_command = "text/vnd.net2phone.commcenter.command" ; //[Feiyu_Xie]
        public readonly  string vnd_radisys_msml_basic_layout = "text/vnd.radisys.msml-basic-layout" ; //[RFC5707]
        public readonly  string vnd_sun_j2me_app_descriptor = "text/vnd.sun.j2me.app-descriptor" ; //[Gary_Adams]
        public readonly  string vnd_trolltech_linguist = "text/vnd.trolltech.linguist" ; //[David_Lee_Lambert]
        public readonly  string vnd_wap_si = "text/vnd.wap.si" ; //[WAP-Forum]
        public readonly  string vnd_wap_sl = "text/vnd.wap.sl" ; //[WAP-Forum]
        public readonly  string vnd_wap_wml = "text/vnd.wap-wml" ; //[Peter_Stark]
        public readonly  string vnd_wap_wmlscript = "text/vnd.wap.wmlscript" ; //[Peter_Stark]
        public readonly  string xml = "text/xml"; //[RFC7303]
        public readonly  string xml_external_parsed_entity = "text/xml-external-parsed-entity" ; //[RFC7303]

    }
}
