using System;
using System.Collections.Generic;
using System.Text;

namespace Iana.MediaTypes
{
    public class Video
    {


        public readonly string Oned_interleaved_parityfec = "video/1d-interleaved-parityfec" ; // [RFC6015]
        public readonly string Threegpp = "video/3gpp" ; // [RFC3839][RFC6381]
        public readonly string Threegpp2 = "video/3gpp2" ; // [RFC4393][RFC6381]
        public readonly string Threegpp_tt = "video/3gpp-tt" ; // [RFC4396]
        public readonly string BMPEG = "video/BMPEG"; // [RFC3555]
        public readonly string BT656 = "video/BT656"; // [RFC3555]
        public readonly string CelB = "video/CelB"; // [RFC3555]
        public readonly string DV = "video/DV"; // [RFC6469]
        public readonly string encaprtp = "video/encaprtp"; // [RFC6849]
        public readonly string example = "video/example"; // [RFC4735]
        public readonly string H261 = "video/H261"; // [RFC4587]
        public readonly string H263 = "video/H263"; // [RFC3555]
        public readonly string H263_1998 = "video/H263-1998"; // [RFC4629]
        public readonly string H263_2000 = "video/H263-2000"; // [RFC4629]
        public readonly string H264 = "video/H264"; // [RFC6184]
        public readonly string H264_RCDO = "video/H264-RCDO"; // [RFC6185]
        public readonly string H264_SVC = "video/H264-SVC"; // [RFC6190]
        public readonly string H265 = "video/H265"; // [RFC7798]
        public readonly string iso_segment = "video/iso.segment"; // [David_Singer][ISO-IEC_JTC1]
        public readonly string JPEG = "video/JPEG"; // [RFC3555]
        public readonly string jpeg2000 = "video/jpeg2000"; // [RFC5371][RFC5372]
        public readonly string mj2 = "video/mj2"; // [RFC3745]
        public readonly string MP1S = "video/MP1S"; // [RFC3555]
        public readonly string MP2P = "video/MP2P"; // [RFC3555]
        public readonly string MP2T = "video/MP2T"; // [RFC3555]
        public readonly string mp4 = "video/mp4"; // [RFC4337][RFC6381]
        public readonly string MP4V_ES = "video/MP4V-ES"; // [RFC6416]
        public readonly string MPV = "video/MPV"; // [RFC3555]
        public readonly string mpeg = ""; // [RFC2045][RFC2046]
        public readonly string mpeg4_generic = "video/mpeg4-generic"; // [RFC3640]
        public readonly string nv = "video/nv"; // [RFC4856]
        public readonly string ogg = "video/ogg"; // [RFC5334][RFC7845]
        public readonly string parityfec = ""; // [RFC5109]
        public readonly string pointer = "video/pointer"; // [RFC2862]
        public readonly string quicktime = "video/quicktime"; // [RFC6381][Paul_Lindner]
        public readonly string raptorfec = "video/raptorfec"; // [RFC6682]
        public readonly string raw = ""; // [RFC4175]
        public readonly string rtp_enc_aescm128 = "video/rtp-enc-aescm128"; // [_3GPP]
        public readonly string rtploopback = "video/rtploopback"; // [RFC6849]
        public readonly string rtx = "video/rtx"; // [RFC4588]
        public readonly string SMPTE292M = "video/SMPTE292M"; // [RFC3497]
        public readonly string ulpfec = "video/ulpfec"; // [RFC5109]
        public readonly string vc1 = "video/vc1"; // [RFC4425]
        public readonly string vnd_CCTV = "video/vnd.CCTV"; // [Frank_Rottmann]
        public readonly string vnd_dece_hd = "video/vnd.dece.hd"; // [Michael_A_Dolan]
        public readonly string vnd_dece_mobile = "video/vnd.dece.mobile"; // [Michael_A_Dolan]
        public readonly string vnd_dece_mp4 = "video/vnd.dece-mp4"; // [Michael_A_Dolan]
        public readonly string vnd_dece_pd = "video/vnd.dece.pd"; // [Michael_A_Dolan]
        public readonly string vnd_dece_sd = "video/vnd.dece.sd"; // [Michael_A_Dolan]
        public readonly string vnd_dece_video = "video/vnd.dece.video"; // [Michael_A_Dolan]
        public readonly string vnd_directv_mpeg = "video/vnd.directv-mpeg"; // [Nathan_Zerbe]
        public readonly string vnd_directv_mpeg_tts = "video/vnd.directv.mpeg-tts"; // [Nathan_Zerbe]
        public readonly string vnd_dlna_mpeg_tts = "video/vnd.dlna.mpeg-tts"; // [Edwin_Heredia]
        public readonly string vnd_dvb_file = "video/vnd.dvb.file"; // [Peter_Siebert][Kevin_Murray]
        public readonly string vnd_fvt = "video/vnd.fvt"; // [Arild_Fuldseth]
        public readonly string vnd_hns_video = "video/vnd.hns.video"; // [Swaminathan]
        public readonly string vnd_iptvforum_1dparityfec_1010 = "video/vnd.iptvforum.1dparityfec-1010"; // [Shuji_Nakamura]
        public readonly string vnd_iptvforum_1dparityfec_2005 = "video/vnd.iptvforum.1dparityfec-2005"; // [Shuji_Nakamura]
        public readonly string vnd_iptvforum_2dparityfec_1010 = "video/vnd.iptvforum.2dparityfec-1010"; // [Shuji_Nakamura]
        public readonly string vnd_iptvforum_2dparityfec_2005 = "video/vnd.iptvforum.2dparityfec-2005"; // [Shuji_Nakamura]
        public readonly string vnd_iptvforum_ttsavc = "video/vnd.iptvforum.ttsavc"; // [Shuji_Nakamura]
        public readonly string vnd_iptvforum_ttsmpeg2 = "video/vnd.iptvforum.ttsmpeg2"; // [Shuji_Nakamura]
        public readonly string vnd_motorola_video = "video/vnd.motorola.video"; // [Tom_McGinty]
        public readonly string vnd_motorola_videop = "video/vnd.motorola.videop"; // [Tom_McGinty]
        public readonly string vnd_mpegurl = "video/vnd-mpegurl"; // [Heiko_Recktenwald]
        public readonly string vnd_ms_playready_media_pyv = "video/vnd.ms-playready.media.pyv"; // [Steve_DiAcetis]
        public readonly string vnd_nokia_interleaved_multimedia = "video/vnd.nokia.interleaved-multimedia"; // [Petteri_Kangaslampi]
        public readonly string vnd_nokia_videovoip = "video/vnd.nokia.videovoip"; // [Nokia]
        public readonly string vnd_objectvideo = "video/vnd.objectvideo"; // [John_Clark]
        public readonly string vnd_radgamettools_bink = "video/vnd.radgamettools.bink"; // [Henrik_Andersson]
        public readonly string vnd_radgamettools_smacker = "video/vnd.radgamettools.smacker"; // [Henrik_Andersson]
        public readonly string vnd_sealed_mpeg1 = "video/vnd.sealed.mpeg1"; // [David_Petersen]
        public readonly string vnd_sealed_mpeg4 = "video/vnd.sealed.mpeg4"; // [David_Petersen]
        public readonly string vnd_sealed_swf = "video/vnd.sealed-swf"; // [David_Petersen]
        public readonly string vnd_sealedmedia_softseal_mov = "video/vnd.sealedmedia.softseal-mov"; // [David_Petersen]
        public readonly string vnd_uvvu_mp4 = "video/vnd.uvvu-mp4"; // [Michael_A_Dolan]
        public readonly string vnd_vivo = "video/vnd-vivo"; // [John_Wolfe]
        public readonly string VP8 = "video/VP8"; // [RFC7741]

    }
}
